ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_PROVIDER_FK
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_PATIENT_FK
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT FK_DRUGTREATMENT_ID
ALTER TABLE SURGERYTREATMENT DROP CONSTRAINT FK_SURGERYTREATMENT_ID
ALTER TABLE RADIOLOGYTREATMENT DROP CONSTRAINT FK_RADIOLOGYTREATMENT_ID
ALTER TABLE RADIOLOGYTREATMENT_DATES DROP CONSTRAINT FK_RADIOLOGYTREATMENT_DATES_RADIOLOGYTREATMENT_FK
DROP TABLE PATIENT CASCADE
DROP TABLE TREATMENT CASCADE
DROP TABLE DRUGTREATMENT CASCADE
DROP TABLE SURGERYTREATMENT CASCADE
DROP TABLE RADIOLOGYTREATMENT CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE RADIOLOGYTREATMENT_DATES CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
